package-lock.json, package.json
- 이번 프로젝트를 위한 기초적인 모듈 세팅을 진행합니다.
- 없음
=> build: default module setting

.gitignore, src/api/apiConfig.js, src/api/authApi.js, src/api/foodApi.js, src/api/noteApi.js, src/api/recipeApi.js, src/api/tipApi.js, src/config/config.js, src/index.js
비동기 데이터 fetching을 위한 React Query 세팅 및 필요 함수 정리
- api 폴더를 생성해 요청 타입을 구별하여 프로젝트 내 client 에서 보내게 될 Http Request 들을 정리 하였습니다.
- React QueryClientProvider 를 사용하여 앱전체적으로 전역 데이터를 세팅을 구축했습니다.
- .env 파일을 만들어 backend url 을 세팅 하였습니다.
- api 폴더 내에 있는 비동기 함수들이 필요한 데이터를 정확히 가지고 오는지 테스트가 되어야합니다.
=> feat: react query setting

public/index.html, src/components/App/index.js, src/components/Footer/index.js, src/components/Header/component.js, src/components/Header/index.js, src/components/Main/index.js, src/config/GlobalStyles.js, src/index.css, src/pages/Home/index.js, src/routes/Routes.js
- 앱의 Home 화면을 구성 하였습니다.
- 공통 헤더를 완성하였습니다.
- 공통 푸터를 완성하였습니다.
- 페이지의 기본 레이아웃을 구성하였습니다.
- 페이지를 Web Accessibility 체크리스트를 기준으로 체크하였습니다.
- components 폴더에서 Header, Main, Footer 컴포넌트가 생성되었습니다.
- index.html lang을 "ko"로 변환(웹 접근성 체크리스트)
- ProfileImg의 alt값 부여(웹접근성 체크리스트)
- 기본 구성
- My Account 버튼 클릭시 모달 오픈 화면
- 헤더 - 모달창 작동하는지, 각링크 잘 잘동하는지, 필요 링크들이 존재하는지
- 푸터 - 푸터 키워드 있는지 여부 테스트
=> Wonil feat starting page

public/index.html, src/index.css, src/pages/Signup/index.js, src/routes/Routes.js
- 회원가입 페이지를 만들었습니다.
- pages 폴더에 Signup 컴포넌트를 구성하였습니다.
-Signup 컴포넌트 테스트하기
=> feat: signup page

src/pages/Login/index.js, src/routes/Routes.js
- 로그인 페이지를 생성하였습니다.
- Signup 컴포넌트의 형식과 같아 해당 형식을 응용하여 만들었습니다. 
- routes를 수정하였습니다.
- pages 폴더에서 Login 페이지가 추가되었습니다.
- 로그인 페이지 테스트 (문구랑, 버튼 작동 여부)
=> feat: login page

package.json, src/api/foodApi.js, src/api/noteApi.js, src/api/recipeApi.js, src/api/tipApi.js, src/pages/PageNewRecipe/index.js, src/pages/PageRecipe/test.js
- API URI 변경
- PageNew Recipe 수정
- API URI 주소 변경했습니다.
- PageNewRecipe 에서는 임시 데이터를 제거하고 진행해주신 로그인 정보를 localStorage에서 가져와 레시피 생성시 담기도록 수정했습니다.
- N/A
- N/A
=> feat: page new recipe functionalities for CRUD

package.json, src/api/apiConfig.js, src/api/authApi.js, src/components/App/component.js, src/components/App/index.js, src/components/Header/index.js, src/pages/PageLogin/index.js, src/pages/PageProfile/index.js, src/routes/Routes.js
- 프로파일 페이지를 완성하였습니다
- 프로파일 페이지에서 별명을 변경할 수 있습니다.
- 별명 변경시 localstorage정보와 login state, mongodb정보 모두 갱신됩니다!
- PageProfile 컴포넌트 로직 추가
- authApi 내용 추가
- 별명 변경되는지 체크하기
- 별명 입력창 입력 가능여부 체크하기
=> Wonil feat profile page making

src/components/Header.js, src/components/Main.js, src/pages/PageRecipes.js
- 헤더의 css를 수정하였습니다.
- 네비게이션용 헤더가 있는 경우 상단고정시키기
- 헤더 컴포넌트의 css 변경
N/A
=> fix: header components

package-lock.json, package.json, src/components/Card.Recipe.js, src/pages/PageRecipes.js
PageRecipe의 레이아웃을 개선하였습니다.
- PageRecipes.js의 내용을 추가하였습니다.
- Card.Recipe.js 의 내용을 추가하였습니다.
- 화면에서 카드가 올바르게 나오는지 테스트
=> fix: PageRecipes-Layout

src/pages/PageRankings.js
- 랭킹 페이지의 기본시작 화면 구성을 완료하였습니다.
- PageRankings 컴포넌트의 내용을 작성하였습니다.
- 기본 화면에 항목들이 나오는지 테스트
- 버튼 눌렀을때 원하는 화면으로 이동하는지 테스트
=> feat: PageRankings

src/components/Header.js, src/pages/PageMyRecipes.js, src/pages/PageRecipes.js
- PageMyRecipe 컴포넌트 레이아웃 완성
- 동시에 PageRecipes 레이아웃을 약간 수정했습니다.
- PageMyRecipe 코드 작성
- PageRecipes styled components css 수정
- 마이레시피 화면에서 해당 카드들이 올바르게 뜨는지
- 해당 레시피 눌렀을때 링크타고 들어가는지.
=> feat: PageMyRecipe

src/components/Input.Search.js, src/pages/PageNewRecipe.js, src/routes/Routes.js
- PageNewRecipe 컴포넌트의 레이아웃을 구성하였습니다.
- input.Search.js 컴포넌틔 레이아웃을 일부 수정하였습니다.
- PageNewRecipe
-input,Search.js
N/A
=> fix PageNewRecipe

public/index.html, src/api/noteApi.js, src/components/Input.Search.js, src/components/Modal.js, src/components/Portal.js, src/pages/PageNewRecipe.js, src/pages/PageRecipes.js, src/pages/PageSingleRecipe.Ingredients.js, src/pages/PageSingleRecipe.MyNote.js, src/pages/PageSingleRecipe.Notes.js, src/pages/PageSingleRecipe.js
- Singe Recipe Page 관련 CREATE UPDATE 작업
- DB 에 있는 추천 단어를 받아서 사용자 입력에 따라 추천을 할 수있고 재사용 될 수 있는 component 의 기능을 개선 하였습니다.
- 재료를 입력하는 곳이  마땅치 않아 Ingredients 컴포넌트를 따로 만들고 Modal 을 사용하여 UI를 구현하였습니다.
- React Query 의 key의 변화에 따라 등록된 query key 를 취소 시키고 최신 데이터를 불러올게 할 수 있도록 crud에 맞춰 구현하였습니다.
- Page Recipe 에서의 사용자 UI logic 과 스타일을 개선했습니다.
- Page Recipe 의 My Note에 해당하는 부분에서 React Query를 사용하여 crud 로직 및 UI를 수정했습니다.
- Page Recipe 의 Notes 에 해당하는 부분에서는 백엔드와 연결하여 list에 데이터를 삽입하고 필요한 부분에서는 props로 하위 컴포넌트로 내리는 작업을 했습니다.
- Page Recipe 에서의 crud 기능은 모두 테스트가 필요합니다.
- React Query 를 사용하는 비동기 처리의 테스트가 필요합니다.
=> Scott feat pagerecipe data

src/components/Header.js, src/components/Input.Search.js
- PageNewRecipe 헤더의 A태그 
- 공통 컴포넌트인 Header 수정
N/A
N/A
=> fix PageNewRecipe Header

src/api/noteApi.js, src/components/Card.Recipe.js, src/components/Loading.js, src/index.css, src/pages/PageMyRecipes.NoteCard.js, src/pages/PageMyRecipes.js, src/pages/PageRecipes.js
- UI개선을 위한 Loading 페이지 추가
-PageRecies
N/A
- 데이터를 불러오는 상황에서 로딩 화면이 등장하는지 테스트
=> Fix page recipes adding loading component

src/api/noteApi.js, src/pages/PageMyRecipes.js, src/pages/PageRankings.js
- 서버쪽에서 MyNote를 가져오는 uri 형식이 달라짐으로 인한 수정
- noteApi.js 의 함수 수정
- 위 함수 수정에 따른 PageMyRecipes.js 함수명 수정
N/A
=> fix noteApi

src/api/tipApi.js, src/components/Header.js, src/components/Input.Search.js, src/config/dateConfig.js, src/pages/PageSingleRecipe.Ingredients.js, src/pages/PageSingleRecipe.MyNote.js, src/pages/PageSingleRecipe.Notes.js, src/pages/PageSingleRecipe.Tips.js, src/pages/PageSingleRecipe.js, src/utils/sortHelper.js
- NoteList UI 작동 로직 개선 및 꿀팁 CRUD 로직 구현
- 현재 Tips 는 진행중이지만 팀의 백엔드 로직 변경에 따라 다시 세팅을 맞춰놓고 해야될것 같아서 Tips 의 구현이 완료되지 않았지마 초기 세팅 상태로 Pull Request 를 올립니다
- NoteList 의 작동 로직 개선 하였습니다. currentNote 상태를 만들어 Note 카드를 누르면 내 노트인지 다른사람의 노트인지 분기처리를 진행했고 내 노트의 확인을 한후 해당 노트를 편집 할수 없도록 제한을 걸었습니다.
- Tips crud 로직에 따라 비동기 처리 함수들을 React Query 로 세팅해 놓았습니다.
- 현재 react query 의 crud 기능이 component 의 내부코드를 좀 길게 만드는 경향이 있는데 추후 모든 react query 의 crud 함수들은 커스텀 훅으로 변경해서 component의 hook 역할을 할 예정입니다.
- NoteList의 UI 작동 방식 테스트와 Tips 관련 crud 함수들의 작동,  UI 변경 결과 및 api 요청 에 대한 테스트가 필요합니다.
=> feat: tip section crud and UI functionality

src/api/foodApi.js, src/api/noteApi.js, src/api/recipeApi.js, src/pages/PageRankings.component.js, src/pages/PageRankings.handler.js, src/pages/PageRankings.js, src/utils/sortHelper.js
- 랭킹 페이지를 완성하였습니다.
- 레시피 / 메뉴 랭킹 항목을 완성하였습니다.
- 시작화면을 최신 레시피 TOP10으로 고정하였습니다.
- 해당 페이지에서 에러나는 부분들을 고쳤습니다.
- 카테고리 랭킹은 현재 한식과 양식으로 고정하였습니다.(추후 쉽게 추가 가능)
- 해당 카테고리 랭킹은 자체 랭킹로직으로 순위를 나열하였습니다. 
- PageRankings와 관련 컴포넌트와 핸들러 파일의 로직이 추가되었습니다.
- 랭킹페이지의 내비게이션 항목을 조금 수정하였습니다.
-랭킹페이지 해당 항목이 정상적으로 작동하는지 테스트 합니다.
=> Wonil feat page rankings recipe top10

src/pages/PageSingleRecipe.MyNote.js, src/utils/sortHelper.js
- git 수정 PR
- git 수정 PR
- N/A
- N/A
=> Scott fix git

src/api/apiConfig.js, src/pages/PageLogin.js, src/pages/PageProfile.js, src/pages/PageRankings.component.js, src/pages/PageRankings.handler.js, src/services/firebase.js
- token 인증을 위한 로직을 일부 적용하였습니다.
- axios 요청시 토큰을 담아서 보냅니다.
- apiConfig 설정 변경
- token 오타 수정
N/A
N/A
=> Wonil feat authenticate by token

package-lock.json, package.json, src/components/App.js, src/components/Card.Recipe.js, src/components/Header.component.js, src/components/Header.js, src/components/Input.Search.js, src/index.js, src/pages/PageHome.js, src/pages/PageLogin.js, src/pages/PageMyRecipes.NoteCard.js, src/pages/PageMyRecipes.js, src/pages/PageNewRecipe.js, src/pages/PageProfile.js, src/pages/PageRankings.component.js, src/pages/PageRankings.js, src/pages/PageRecipes.js, src/pages/PageSingleRecipe.js
-웹 접근성을 위한 코드 정리 및 변경 작업 1차결과물
- 탭만으로 모든 항목 이동하고 선택하기
- 탭 이동시 해당 아이콘이 정확하게 보여지게 설정하기. 
- (체크리스트)Inputs use autocomplete where appropriate.
- useQuery provider 위치 변경
- 레시피 생성시 해당 페이지로 바로 이동하기 처리
- 필요한 input에서 자동 완성 기능 추가하기
- (체크리스트) Use the a element for links
- Page Title Rename
- Pages 파일들 대부분을 조건에 맞게 변경하였습니다.
N/A
N/A
=> Wonil feat web accessibility

src/components/Input.Search.js, src/constants/voice-command.js, src/hooks/ingredient-speech-control.js, src/hooks/note-speech-control.js, src/pages/PageSingleRecipe.Ingredients.js, src/pages/PageSingleRecipe.MyNote.js, src/pages/PageSingleRecipe.Tips.js, src/pages/PageSingleRecipe.js, src/utils/speechSynthesis.js, src/utils/voiceHelper.js
- Web Speech API를 이용해 PageSingleRecipe 의 조작을 구현했습니다.
- Web Speech API의 SpeechRecognition 과 Speech Synthesis 를 사용해 사용자가 명령을 시작하는 타이밍을 잡고 그 명령으로 조작을 하는 로직을 구현했습니다.
- 음성 조작은 component 별 hook 으로 따로 제작하였습니다.
- 음성으로 조작 가능한 기능 -> 영상 시작, 영상 멈추기, 영상 앞으로, 영상 뒤고, 페이지 내 navigation, 레시피 영상 좋아요, 노트 읽어주기, 재료 읽어 주기, 노트 저장, 삭제, 비공개 처리, 재료 등록 및 저장(버그가 있어서 처리 필요)
- 저장되었다는 메시지를 제작했습니다.
- CSS 를 통해 명령이 시작되었을 시 듣고 있는 모양 제작하였습니다.
- Typewriter 를 이용해 명령을 영상 하단에 표시했습니다.
- 음성 명령어 정리했습니다.
- 음성 관련 조작이 손으로 하는 조작과 차이가 없고 같은 기능을 하고 있는지 테스트가 되어야 합니다.
=> feat: voice control single recipe page, note and ingredients

src/components/Card.Recipe.js, src/components/Header.component.js, src/components/Input.Search.js, src/pages/PageNewRecipe.js, src/pages/PageRankings.component.js, src/pages/PageSingleRecipe.js
- img에 role 속성을 부여하여 스크린리더 사용시 button으로 인식되게 했습니다.
- img alt에 구체적인 명칭을 부여했습니다.
N/A
N/A
=> feat:web Accessibility

src/components/Header.component.js, src/components/Header.js, src/components/ModalGuideSinglePage.js, src/components/VoiceControlGuide.js, src/pages/PageSingleRecipe.js
- GuideModal의 위치와 크기,css를 조정하였습니다.
- GuideModal 수정
- GuideModalSinglePage 생성
- 모달 뜨는지 체크
=> fix: GuideModal Configuration

package.json, src/components/Header.component.js, src/components/Header.js
- Header의 css를 고쳤습니다. 
- Header.js
N/A
N/A
=> fix: Header css

package.json
- 배포를 위해 프록시 설정을 제거합니다.
- package.json
N/A
N/A
=> fix: delete proxy config

.gitignore
- vercel cli추가해서 gitignore 에 내용 추가되었습니다.
N/A
N/A
N/A
=> build: vercel cli

src/api/apiConfig.js
- cors 이슈 해결을 위한 옵션 추가!
- axiot옵션 추가
N/A
N/A
=> fix: withCredentials true

src/api/apiConfig.js
- cors 테스트입니다.
- axios 옵션 테스트입니다.
N/A
N/A
=> build: test credetials

src/pages/PageSingleRecipe.MyNote.js
=> fix: css recording box
